import type { Metadata } from "next";
import './styles/globals.css'
import { PokemonFilterProvider } from './contexts/pokemon-filter-context';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <PokemonFilterProvider>
          {children}
        </PokemonFilterProvider>
      </body>
    </html>
  );
}
